CREATE TRIGGER eliminar_detalles_al_borrar_factura
BEFORE DELETE ON FACTURACOMPRA
FOR EACH ROW
BEGIN
    DELETE FROM DETALLECOMPRA
    WHERE IDCOMPRA = OLD.IDCOMPRA;
END;

CREATE TRIGGER trigger_eliminar_forma_farmaceutica
AFTER DELETE ON FORMAFARMACEUTICA
FOR EACH ROW
BEGIN
    DELETE FROM ARTICULO
    WHERE IDFORMAFARMACEUTICA = OLD.IDFORMAFARMACEUTICA;
END;

CREATE TRIGGER trigger_eliminar_marca
AFTER DELETE ON MARCA
FOR EACH ROW
BEGIN
    DELETE FROM ARTICULO
    WHERE IDMARCA = OLD.IDMARCA;
END;

CREATE TRIGGER trigger_eliminar_viaadministracion
AFTER DELETE ON VIAADMINISTRACION
FOR EACH ROW
BEGIN
    DELETE FROM ARTICULO
    WHERE IDVIAADMINISTRACION = OLD.IDVIAADMINISTRACION;
END;

CREATE TRIGGER trigger_eliminar_doctor
AFTER DELETE ON DOCTOR
FOR EACH ROW
BEGIN
    DELETE FROM RECETA
    WHERE IDDOCTOR = OLD.IDDOCTOR;
END;

CREATE TRIGGER eliminar_detalles_venta_al_borrar_factura_venta
BEFORE DELETE ON FACTURAVENTA
FOR EACH ROW
BEGIN
    DELETE FROM DETALLEVENTA
    WHERE IDVENTA = OLD.IDVENTA;
END;

