--FACTURACOMPRA, DETALLECOMPRA, PROVEEDOR
CREATE TRIGGER eliminar_detalles_al_borrar_factura
BEFORE DELETE ON FACTURACOMPRA
FOR EACH ROW
BEGIN
    DELETE FROM DETALLECOMPRA
    WHERE IDCOMPRA = OLD.IDCOMPRA;
END;

CREATE TRIGGER eliminar_facturas_al_borrar_proveedor
BEFORE DELETE ON PROVEEDOR
FOR EACH ROW
BEGIN
    DELETE FROM FACTURACOMPRA
    WHERE IDPROVEEDOR = OLD.IDPROVEEDOR;
END;
--FIN

CREATE TRIGGER trigger_eliminar_forma_farmaceutica
AFTER DELETE ON FORMAFARMACEUTICA
FOR EACH ROW
BEGIN
    DELETE FROM ARTICULO
    WHERE IDFORMAFARMACEUTICA = OLD.IDFORMAFARMACEUTICA;
END;

CREATE TRIGGER trigger_eliminar_marca
AFTER DELETE ON MARCA
FOR EACH ROW
BEGIN
    DELETE FROM ARTICULO
    WHERE IDMARCA = OLD.IDMARCA;
END;

CREATE TRIGGER trigger_eliminar_viaadministracion
AFTER DELETE ON VIAADMINISTRACION
FOR EACH ROW
BEGIN
    DELETE FROM ARTICULO
    WHERE IDVIAADMINISTRACION = OLD.IDVIAADMINISTRACION;
END;

CREATE TRIGGER trigger_eliminar_doctor
AFTER DELETE ON DOCTOR
FOR EACH ROW
BEGIN
    DELETE FROM RECETA
    WHERE IDDOCTOR = OLD.IDDOCTOR;
END;

CREATE TRIGGER eliminar_detalles_venta_al_borrar_factura_venta
BEFORE DELETE ON FACTURAVENTA
FOR EACH ROW
BEGIN
    DELETE FROM DETALLEVENTA
    WHERE IDVENTA = OLD.IDVENTA;
END;

CREATE TRIGGER eliminar_subcategorias_al_borrar_categoria
BEFORE DELETE ON CATEGORIA
FOR EACH ROW
BEGIN
    DELETE FROM SUBCATEGORIA
    WHERE IDCATEGORIA = OLD.IDCATEGORIA;
END;

CREATE TRIGGER eliminar_articulo_al_borrar_sub_categoria
BEFORE DELETE ON SUBCATEGORIA
FOR EACH ROW
BEGIN
    DELETE FROM ARTICULO
    WHERE IDSUBCATEGORIA = OLD.IDSUBCATEGORIA;
END;

CREATE TRIGGER eliminar_referencias_de_articulo_al_borrarlo
BEFORE DELETE ON ARTICULO
FOR EACH ROW
BEGIN
    DELETE FROM DETALLEEXISTENCIA
    WHERE IDARTICULO = OLD.IDARTICULO;

    DELETE FROM DETALLECOMPRA
    WHERE IDARTICULO = OLD.IDARTICULO;

    DELETE FROM DETALLEVENTA
    WHERE IDARTICULO = OLD.IDARTICULO;

END;

--FACTURAVENTA, CLIENTE
CREATE TRIGGER eliminar_facturas_venta_al_borrar_cliente
BEFORE DELETE ON CLIENTE
FOR EACH ROW
BEGIN
    DELETE FROM FACTURAVENTA
    WHERE IDCLIENTE = OLD.IDCLIENTE;
END;
--FIN
